// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIbMxEiT9Ec6IM2jy8OkMYq2y89Mo5mgs',
    appId: '1:64721660183:web:4c1a3c8a467c12ef6baf52',
    messagingSenderId: '64721660183',
    projectId: 'myweather-5ea7d',
    authDomain: 'myweather-5ea7d.firebaseapp.com',
    storageBucket: 'myweather-5ea7d.appspot.com',
    measurementId: 'G-XCJFGDVP9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLgTU7V0MJLYLHhGj7EyP9ecOJyNA5SMA',
    appId: '1:64721660183:android:05e76c3337dad8f36baf52',
    messagingSenderId: '64721660183',
    projectId: 'myweather-5ea7d',
    storageBucket: 'myweather-5ea7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTlfHGdx75Swl7nAooJ4V43iZky-0dpS0',
    appId: '1:64721660183:ios:f6c2e7002c68e5566baf52',
    messagingSenderId: '64721660183',
    projectId: 'myweather-5ea7d',
    storageBucket: 'myweather-5ea7d.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTlfHGdx75Swl7nAooJ4V43iZky-0dpS0',
    appId: '1:64721660183:ios:f6c2e7002c68e5566baf52',
    messagingSenderId: '64721660183',
    projectId: 'myweather-5ea7d',
    storageBucket: 'myweather-5ea7d.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIbMxEiT9Ec6IM2jy8OkMYq2y89Mo5mgs',
    appId: '1:64721660183:web:0279d1baa2b123b76baf52',
    messagingSenderId: '64721660183',
    projectId: 'myweather-5ea7d',
    authDomain: 'myweather-5ea7d.firebaseapp.com',
    storageBucket: 'myweather-5ea7d.appspot.com',
    measurementId: 'G-HY0CEXE65K',
  );
}
